spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/ZIPKIN
    username: root
    password: root
    initialize: true
    continue-on-error: true
zipkin:
  storage:
    type: mysql
